export enum Commands {
    NOOP = "NOOP",
    PING = "PING",
    PING_BACK = "PING_BACK",
    KEEPALIVE = "KEEPALIVE",
    VOLUME_MUTE = "VOLUME_MUTE",
    VOLUME_DOWN = "VOLUME_DOWN",
    VOLUME_UP = "VOLUME_UP",
    MEDIA_NEXT_TRACK = "MEDIA_NEXT_TRACK",
    MEDIA_PREV_TRACK = "MEDIA_PREV_TRACK",
    MEDIA_STOP = "MEDIA_STOP",
    MEDIA_PLAY_PAUSE = "MEDIA_PLAY_PAUSE",
}
